"""Initial migration

Revision ID: e3b6f2bd4373
Revises: 
Create Date: 2026-04-01 17:57:09.425338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b6f2bd4373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('auth_permission_content_type_id_2f476e4b'), table_name='auth_permission')
    op.drop_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('django_session_expire_date_a5c62663'), table_name='django_session')
    op.drop_table('django_session')
    op.drop_table('auth_group')
    op.drop_index(op.f('blog_post_author_id_dd7a8485'), table_name='blog_post')
    op.drop_index(op.f('blog_post_category_id_c326dbf8'), table_name='blog_post')
    op.drop_index(op.f('blog_post_location_id_040b0a05'), table_name='blog_post')
    op.drop_table('blog_post')
    op.drop_index(op.f('blog_comment_author_id_4f11e2e0'), table_name='blog_comment')
    op.drop_index(op.f('blog_comment_post_id_580e96ef'), table_name='blog_comment')
    op.drop_table('blog_comment')
    op.drop_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), table_name='django_content_type')
    op.drop_table('django_content_type')
    op.drop_index(op.f('django_admin_log_content_type_id_c4bce8eb'), table_name='django_admin_log')
    op.drop_index(op.f('django_admin_log_user_id_c564eba6'), table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_table('auth_user')
    op.drop_table('blog_location')
    op.drop_index(op.f('auth_user_groups_group_id_97559544'), table_name='auth_user_groups')
    op.drop_index(op.f('auth_user_groups_user_id_6a12ed8b'), table_name='auth_user_groups')
    op.drop_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index(op.f('auth_group_permissions_group_id_b120cbf9'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_permission_id_84c5c92e'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('django_migrations')
    op.drop_table('blog_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('applied', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), 'auth_group_permissions', ['group_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), 'auth_user_groups', ['user_id', 'group_id'], unique=1)
    op.create_index(op.f('auth_user_groups_user_id_6a12ed8b'), 'auth_user_groups', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_groups_group_id_97559544'), 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('blog_location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action_time', sa.DATETIME(), nullable=False),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), nullable=False),
    sa.Column('change_message', sa.TEXT(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_flag', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('"action_flag" >= 0'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), 'django_content_type', ['app_label', 'model'], unique=1)
    op.create_table('blog_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('blog_comment_post_id_580e96ef'), 'blog_comment', ['post_id'], unique=False)
    op.create_index(op.f('blog_comment_author_id_4f11e2e0'), 'blog_comment', ['author_id'], unique=False)
    op.create_table('blog_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('pub_date', sa.DATETIME(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('location_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['blog_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('blog_post_location_id_040b0a05'), 'blog_post', ['location_id'], unique=False)
    op.create_index(op.f('blog_post_category_id_c326dbf8'), 'blog_post', ['category_id'], unique=False)
    op.create_index(op.f('blog_post_author_id_dd7a8485'), 'blog_post', ['author_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', sa.TEXT(), nullable=False),
    sa.Column('expire_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), 'auth_permission', ['content_type_id', 'codename'], unique=1)
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    # ### end Alembic commands ###
